#
# 'EnableEFLOWTPM'
#
# Generated by: Fran Aguilera
#
# Generated on: 04/05/2022
#
#Requires -RunAsAdministrator
Stop-EflowVm
Remove-Module AzureEFLOW
((Get-Content -path $env:PSModulePath\AzureEFLOW\AzureEFLOW.psm1 -Raw) -replace 'Get-NetAdapter','Get-NetAdapter -IncludeHidden') | Set-Content -Path $env:PSModulePath\AzureEFLOW\AzureEFLOW.psm1
Import-Module AzureEFLOW
Start-EflowVm
Set-EflowVmFeature -feature 'DpsTpm' -Enable